import { Inter } from "next/font/google";
import "./globals.css";
import 'tailwindcss/tailwind.css'
import { FavoritesProvider } from '@/app/context/FavoritesContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Cocktail DB APP",
  description: "Generated by Damith Weerawardana create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <FavoritesProvider>{children}</FavoritesProvider>
      </body>
    </html>
  );
}
